apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: tap-gui-catalog-info
  description: A sample catalog for Backstage
  annotations:
    'backstage.io/techdocs-ref': dir:.
spec:
  targets:
    - ./components/tap-gui.yaml
    - ./groups/default-org.yaml
    - ./systems/tap-gui-system.yaml
    - ./domains/tap-gui-domain.yaml
    - https://github.com/sample-accelerators/spring-petclinic/blob/tap-1.1/catalog/catalog-info.yaml
    - https://github.com/sample-accelerators/tanzu-java-web-app/blob/tap-1.0/catalog/catalog-info.yaml
    - https://github.com/eoghank/spring-petclinic-rest/blob/main/catalog/catalog-info.yaml
    - https://github.com/eoghank/restservice/blob/main/catalog/catalog-info.yaml
    - https://github.com/eoghank/java-rest-service/blob/main/catalog/catalog-info.yaml
